### PR TITLE
Use Inline key and switch to html

### PR DESCRIPTION
**Pull request by Clashkid155**
Switched to html to avoid inconvenient Markdown escaping 😒.
It should look like this

### CODE REVIEW

**Comment by LordGhostX** [comment]
Hi, have you considered how the job messages can be shared to other platforms aside telegram with the Apply button. I purposely left the application links in plain text so the updates can be easily copied and pasted on Twitter, Slack, WhatsApp or even sent in emails to other people. But with this button any text shared will not include the application links. Do you have any solution for this?

**Comment by Clashkid155** [comment]
Didn't think of this situation. I don't have any solution but i will change the button to text with url embedded. How does that sound ?  The issue with this approach is, the link can be copied but when it comes to sharing to other platform i don't know if the link will be retained.

**Comment by LordGhostX** [comment]
How about we add the application link to the text like it is originally then add the apply button beneath, so it has a really cool look on telegram like the image above then when copied to other social media it still has the link users can apply with

**Comment by Clashkid155** [comment]
I can do that. Give me a minute

**Comment by LordGhostX** [comment]
Also, Instead of adding the apply button to every function that scrapes for new jobs you can just add it to the send_job_to_users() function so you don't have to repeat code

**Comment by Clashkid155** [comment]
I other for me to do that i will have to also pass url of the jobs.

**Comment by LordGhostX** [comment]
yeah, that's true. No problem with that

**Comment by Clashkid155** [comment]
Done

**Comment by Clashkid155** [comment]
@LordGhostX Hope you didn't merge this commit. Merge the open commit this is already closed.

**Pull request merged**
